### PR TITLE
fix: load xcode before `e init` 

### LINKED ISSUE #513: Updating `depot_tools` requires Xcode but doesn't ensure that Xcode exists
### Operating System

macOS 13.5.1, arm64

### To Reproduce

1. If you already have everything installed, remove `~/.electron_build_tools/third_party/Xcode`.
2. [Set up your local Electron environment](https://www.electronjs.org/docs/latest/development/pull-requests#setting-up-your-local-environment).
3. [Install `build-tools`](https://github.com/electron/build-tools#installation).
4. In the `electron` directory, run `e init --root=~/electron depot-tools-testing`.

### Expected Behavior

Everything to work correctly.

### Actual Behavior

The following was logged:

```
Checking for build-tools updates
Running "git pull --rebase --autostash" in /Users/ntautges/.electron_build_tools
build-tools is up-to-date
Creating /Users/ntautges/electron
Cloning "depot_tools" into /Users/ntautges/.electron_build_tools/third_party/depot_tools
Updating /Users/ntautges/.electron_build_tools/third_party/depot_tools
Running "/Users/ntautges/.electron_build_tools/third_party/depot_tools/update_depot_tools"
Updating depot_tools...
xcrun: error: missing DEVELOPER_DIR path: /Users/ntautges/.electron_build_tools/third_party/Xcode/Xcode.app
depot_tools update failed. Couldn't fetch main branch.
Retry later or reclone depot_tools
xcrun: error: missing DEVELOPER_DIR path: /Users/ntautges/.electron_build_tools/third_party/Xcode/Xcode.app
ERROR Error: Command failed: /Users/ntautges/.electron_build_tools/third_party/depot_tools/update_depot_tools
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at depotExecFileSync (/Users/ntautges/.electron_build_tools/src/utils/depot-tools.js:131:23)
    at updateDepotTools (/Users/ntautges/.electron_build_tools/src/utils/depot-tools.js:18:5)
    at Object.ensureDepotTools [as ensure] (/Users/ntautges/.electron_build_tools/src/utils/depot-tools.js:30:5)
    at runGClientConfig (/Users/ntautges/.electron_build_tools/src/e-init.js:79:9)
    at ensureRoot (/Users/ntautges/.electron_build_tools/src/e-init.js:109:5)
    at Command.<anonymous> (/Users/ntautges/.electron_build_tools/src/e-init.js:179:7)
    at Command.listener [as _actionHandler] (/Users/ntautges/.electron_build_tools/node_modules/commander/lib/command.js:480:17)
```

### Additional Information

If you create the config by removing `~/electron` and running `e init --root=~/electron depot-tools-testing` and run `e sync`, it also happens:

```
Creating /Users/ntautges/electron/src
Running "gclient sync --with_branch_heads --with_tags -vv" in /Users/ntautges/electron/src
Updating depot_tools...
xcrun: error: missing DEVELOPER_DIR path: /Users/ntautges/.electron_build_tools/third_party/Xcode/Xcode.app
depot_tools update failed. Couldn't fetch main branch.
Retry later or reclone depot_tools
xcrun: error: missing DEVELOPER_DIR path: /Users/ntautges/.electron_build_tools/third_party/Xcode/Xcode.app
ERROR Error: spawnSync /bin/sh ENOENT
    at Object.spawnSync (node:internal/child_process:1110:20)
    at spawnSync (node:child_process:871:24)
    at Object.execSync (node:child_process:952:15)
    at setRemotes (/Users/ntautges/.electron_build_tools/src/e-sync.js:29:8)
    at runGClientSync (/Users/ntautges/.electron_build_tools/src/e-sync.js:62:5)
    at Command.<anonymous> (/Users/ntautges/.electron_build_tools/src/e-sync.js:77:7)
    at Command.listener [as _actionHandler] (/Users/ntautges/.electron_build_tools/node_modules/commander/lib/command.js:480:17)
    at /Users/ntautges/.electron_build_tools/node_modules/commander/lib/command.js:1234:65
    at Command._chainOrCall (/Users/ntautges/.electron_build_tools/node_modules/commander/lib/command.js:1151:12)
    at Command._parseCommand (/Users/ntautges/.electron_build_tools/node_modules/commander/lib/command.js:1234:27)
```

The built-in version of git on macOS is a shim around the Xcode Command Line Tools install, so when [`DEVELOPER_DIR` is set](https://github.com/electron/build-tools/blob/ac4f9a9063f29baa5b356a71b8182b36889a5405/src/utils/depot-tools.js#L80) when `e load-xcode` hasn't been run yet, it looks to an installation of Xcode that hasn't yet been installed and causes the error.

[`e build` ensures that Xcode is installed before running](https://github.com/electron/build-tools/blob/ac4f9a9063f29baa5b356a71b8182b36889a5405/src/e-build.js#L83). Would doing that some thing for `e init` and `e sync` (and whatever other commands need it) be a proper fix for this? Regardless, I'd be willing to take a crack at it.

Thank you for taking a look at this.

### PR DESCRIPTION
**Pull request by alicelovescake**
This PR:
- [x] fixes #513 and loads xcode before `e init`  runs git commands inside build tools

### CODE REVIEW

**Review by georgexu99 — APPROVED** [review]
🔥

**Comment by alicelovescake** [comment]
@codebytere You mentioned in[ the issue ](https://github.com/electron/build-tools/issues/513) to tag you in a PR. I ran into the same problem on my Mac so made the fix, let me know if you have any feedback on this change!

File: src/e-init.js [hunk 1]
```diff
@@ -182,6 +182,13 @@ program
       const opts = { stdio: 'inherit' };
       childProcess.execFileSync(process.execPath, [e, 'use', name], opts);
 
+      // ensure xcode is loaded
+      if (process.platform === 'darwin') {
+        loadXcode(true);
+      }
+
+      ensureRoot(config, !!options.force);
+
```
Comment (alicelovescake) [inline src/e-init.js:191]: FYI: I structured the functions this way because `loadXcode` has to come after the saving of the config and once `e use` has been called because it uses the config. `ensureRoot` relies on xcode so it comes afterward. Let me know if this looks correct or not!

**Review by ckerr — APPROVED** [review]
CC @codebytere who also has an Xcode PR in-flight

**Comment by dsanders11** [comment]
@alicelovescake, looks like there's test failures on CI that need to be resolved here.

**Comment by alicelovescake** [comment]
> @alicelovescake, looks like there's test failures on CI that need to be resolved here.

Thanks! I did see that last week. My tests were all passing locally so I'm not sure why it's failing in CI. So I'm rerunning the workflow and seeing what happens!

**Comment by alicelovescake** [comment]
@ckerr @dsanders11 Any advice for the failing test in CI? It passes locally and I've re-ran the CI workflow and it's still failing on the same tests. I can close the PR if there are going to be future changes to loading xcode on `e init`.

**Comment by alicelovescake** [comment]
Update: 
- Current test in CI is failing because it can't support `loadXcode`. Currently trying to mock the function in e init tests but [test runs using ](https://github.com/electron/build-tools/blob/main/tests/sandbox.js#L32)execFileSync which is in a different process. 
- Removed change to `e sync` because I wanted to keep the PR small and technically the user should have xcode set up with init before running sync so it might be redundant.

**Review by codebytere — APPROVED** [review]

**Review by dsanders11 — APPROVED** [review]
