### PR TITLE
fix: call gclient directly instead of via Python

### LINKED ISSUE #330: ImportError: No module named httplib2
```
dsanders@Davids-MacBook-Pro ~ % e init --root=~/electron --bootstrap testing        
Checking for build-tools updates
Running "git pull --rebase --autostash" in /Users/dsanders/.electron_build_tools
build-tools is up-to-date
Cloning "depot_tools" into /Users/dsanders/.electron_build_tools/third_party/depot_tools
Updating /Users/dsanders/.electron_build_tools/third_party/depot_tools
Running "/Users/dsanders/.electron_build_tools/third_party/depot_tools/update_depot_tools"
Running "python /Users/dsanders/.electron_build_tools/third_party/depot_tools/gclient.py config --name src/electron --unmanaged https://github.com/electron/electron" in /Users/dsanders/electron
Traceback (most recent call last):
  File "/Users/dsanders/.electron_build_tools/third_party/depot_tools/gclient.py", line 108, in <module>
    import gclient_scm
  File "/Users/dsanders/.electron_build_tools/third_party/depot_tools/gclient_scm.py", line 29, in <module>
    import gerrit_util
  File "/Users/dsanders/.electron_build_tools/third_party/depot_tools/gerrit_util.py", line 16, in <module>
    import httplib2
ImportError: No module named httplib2
ERROR Error: Command failed: python /Users/dsanders/.electron_build_tools/third_party/depot_tools/gclient.py config --name src/electron --unmanaged https://github.com/electron/electron
    at checkExecSyncError (node:child_process:828:11)
    at Object.execFileSync (node:child_process:866:15)
    at Object.depotExecFileSync [as execFileSync] (/Users/dsanders/.electron_build_tools/src/utils/depot-tools.js:121:16)
    at runGClientConfig (/Users/dsanders/.electron_build_tools/src/e-init.js:85:9)
    at ensureRoot (/Users/dsanders/.electron_build_tools/src/e-init.js:102:5)
    at Object.<anonymous> (/Users/dsanders/.electron_build_tools/src/e-init.js:192:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

Seeing this on macOS, and @RaisinTen sees it on Windows, so seems like an across the board error.

### PR DESCRIPTION
**Pull request by dsanders11**
Fixes #330.

I believe that issue was caused by [this CL landing](https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3445785) which moved `gclient` to Python 3, and the way `build-tools` was invoking `gclient` skips over the `vpython3` stuff, so the `httplib2` library wasn't being installed in the venv.

### CODE REVIEW

**Review by RaisinTen — COMMENTED** [review]
Additionally applying this patch should fix this error for Windows 
```diff
diff --git a/src/utils/depot-tools.js b/src/utils/depot-tools.js
index 05934c5..7772cb5 100644
--- a/src/utils/depot-tools.js
+++ b/src/utils/depot-tools.js
@@ -115,6 +115,8 @@ function depotSpawnSync(config, cmd, args, opts_in) {
 function depotExecFileSync(config, exec, args, opts_in) {
   if (exec === 'python' && !path.isAbsolute(args[0])) {
     args[0] = path.resolve(DEPOT_TOOLS_DIR, args[0]);
+  } else if (exec === 'gclient' && process.platform === 'win32') {
+    exec = path.resolve(DEPOT_TOOLS_DIR, `${exec}.bat`);
   }
   const opts = depotOpts(config, opts_in);
   console.log(color.childExec(exec, args, opts));
```

File: src/e-init.js [hunk 1]
```diff
@@ -70,9 +70,8 @@ function createConfig(options) {
 function runGClientConfig(config) {
   const { root } = config;
   depot.ensure();
-  const exec = 'python';
+  const exec = 'gclient';
```
Comment (RaisinTen) [inline src/e-init.js:73]:
```suggestion
  const exec = process.platform === 'win32' ? 'gclient.bat' : 'gclient';
```

File: src/e-sync.js [hunk 2]
```diff
@@ -42,8 +42,8 @@ function runGClientSync(syncArgs, syncOpts) {
 
   depot.ensure();
 
-  const exec = 'python';
-  const args = ['gclient.py', 'sync', '--with_branch_heads', '--with_tags', '-vv', ...syncArgs];
+  const exec = 'gclient';
```
Comment (RaisinTen) [inline src/e-sync.js:45]:
```suggestion
  const exec = process.platform === 'win32' ? 'gclient.bat' : 'gclient';
```

**Review by RaisinTen — COMMENTED** [review]
A more contained fix

File: src/e-init.js (hunk 1 above)
Comment (dsanders11) [reply src/e-init.js:73]: I don't think this is necessary, `gclient` should be accessible without using the `.bat` version.

**Comment by dsanders11** [comment]
Pinging @ckerr and @codebytere since this is ready for review.

**Review by codebytere — APPROVED** [review]
